<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_didimus08_Dim</name>
   <tag></tag>
   <elementGuidId>0e90b3cd-210f-4342-a7ff-837c12115ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-root']/section/nav/div[2]/div/div/div[2]/div[2]/div[2]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z556c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>didimus08_Dim.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-root&quot;)/section[@class=&quot;_9eogI E3X2T&quot;]/nav[@class=&quot;NXc7H jLuN9&quot;]/div[@class=&quot;_8MQSO  Cx7Bp&quot;]/div[@class=&quot;_lz6s&quot;]/div[@class=&quot;MWDvN&quot;]/div[@class=&quot;LWmhU _0aCwM&quot;]/div[2]/div[@class=&quot;drKGC&quot;]/div[@class=&quot;fuqBx&quot;]/a[@class=&quot;yCE8d  JvDyy&quot;]/div[@class=&quot;z556c&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-root']/section/nav/div[2]/div/div/div[2]/div[2]/div[2]/div/a/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2020 Instagram from Facebook'])[1]/following::div[17]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a/div</value>
   </webElementXpaths>
</WebElementEntity>
